// src/features/sidebar/sidebarSlice.js

import { createSlice } from '@reduxjs/toolkit';

// Initial state of the sidebar
const initialState = {
  isSlideOpen: true,  // Sidebar starts open
};

// Create a slice for the sidebar state
const sidebarSlice = createSlice({
  name: 'sidebar',  // Name of the slice
  initialState,
  reducers: {
    toggleSidebar: (state) => {
      // Toggle the sidebar state (open or closed)
      state.isSlideOpen = !state.isSlideOpen;
    },
    setSidebarState: (state, action) => {
      // Set the sidebar state directly from an outside action
      state.isSlideOpen = action.payload;
    },
  },
});

// Export the actions generated by the slice
export const { toggleSidebar, setSidebarState } = sidebarSlice.actions;

// Export the reducer for this slice
export default sidebarSlice.reducer;
